// Style reminder: Nắng Trên Luống Đất — mọi phản hồi là một dấu hiệu chăm sóc nhỏ, với paper UI và Clay Sprout #C9784B.
import { useEffect, useMemo, useRef, useState, type MouseEvent, type PointerEvent } from "react";
import { Engine } from "@babylonjs/core/Engines/engine";
import { createGameScene } from "@/game/scene";
import { Leaf, Droplets, Heart, Sun, Sprout, Shovel, Hand, Sparkles, Cat, Rabbit, RotateCcw, Volume2, VolumeX, Flower2, TreePine, Bird, LockKeyhole } from "lucide-react";
import { toast } from "sonner";

const logoUrl = "/manus-storage/vuon-nho-logo_98aa6ada.png";
const SAVE_KEY = "vuon-nho-chill-save-v2";
type PlotState = "empty" | "sprout" | "growing" | "ready";
type Plot = { state: PlotState; plant: string; progress: number };
type PetName = "Miu" | "Bông";
type SeedKey = "sunflower" | "tomato" | "lavender" | "strawberry";
type DecorKey = "bench" | "birdhouse" | "lantern";
type StickerKey = "lucky" | "sleepy" | "tea" | "sparkle";
type SaveData = { plots: Plot[]; water: number; leaves: number; selectedPlot: number; selectedPet: PetName; petMood: number; day: number; seeds: Record<SeedKey, number>; decor: DecorKey[]; soundOn: boolean; selectedSeed: SeedKey; storySeen: boolean; luckyDew: number; stickers: StickerKey[]; musicVolume: number; sfxVolume: number };

const initialPlots: Plot[] = [
  { state: "ready", plant: "Cà chua bi", progress: 100 }, { state: "growing", plant: "Húng quế", progress: 68 },
  { state: "sprout", plant: "Hoa cúc", progress: 28 }, { state: "empty", plant: "", progress: 0 },
];
const seedCatalog: Record<SeedKey, { label: string; icon: string; days: string; color: string }> = {
  sunflower: { label: "Hướng dương", icon: "🌻", days: "3 ngày", color: "#e9b85e" }, tomato: { label: "Cà chua bi", icon: "🍅", days: "2 ngày", color: "#db7562" }, lavender: { label: "Oải hương", icon: "💜", days: "4 ngày", color: "#a58abf" }, strawberry: { label: "Dâu nhỏ", icon: "🍓", days: "3 ngày", color: "#d86668" },
};
const decorCatalog: Record<DecorKey, { label: string; icon: string; cost: number }> = { bench: { label: "Ghế gỗ", icon: "🪵", cost: 18 }, birdhouse: { label: "Nhà chim", icon: "🐦", cost: 26 }, lantern: { label: "Đèn lồng", icon: "🏮", cost: 34 } };
const stageCopy: Record<PlotState, string> = { empty: "Luống trống", sprout: "Mầm non", growing: "Đang lớn", ready: "Thu hoạch" };
const stickerCatalog: Record<StickerKey, { icon: string; label: string; note: string }> = { lucky: { icon: "🐝🍀", label: "Ong ôm cỏ 4 lá", note: "Chúc bạn một ngày tràn đầy may mắn!" }, sleepy: { icon: "🐝💤", label: "Ong ngủ trên cánh hoa", note: "Một khoảng nghỉ thật êm." }, tea: { icon: "🐝🍵", label: "Ong nhâm nhi trà", note: "Hợp với một ngày mưa chill chill." }, sparkle: { icon: "🐝✨", label: "Ong thả tim lấp lánh", note: "Bạn đã làm tốt rồi." } };
const defaultSave: SaveData = { plots: initialPlots, water: 6, leaves: 24, selectedPlot: 0, selectedPet: "Miu", petMood: 82, day: 7, seeds: { sunflower: 3, tomato: 2, lavender: 1, strawberry: 1 }, decor: [], soundOn: true, selectedSeed: "sunflower", storySeen: false, luckyDew: 0, stickers: [], musicVolume: .16, sfxVolume: .55 };

function loadSave(): SaveData { try { const raw = localStorage.getItem(SAVE_KEY); return raw ? { ...defaultSave, ...JSON.parse(raw) } : defaultSave; } catch { return defaultSave; } }
function playTone(kind: "water" | "harvest" | "pet" | "plant" | "day" | "click" | "purr" | "bee", enabled: boolean, volume = .55) {
  if (!enabled || typeof window === "undefined") return;
  try { const Ctx = window.AudioContext || (window as typeof window & { webkitAudioContext?: typeof AudioContext }).webkitAudioContext; if (!Ctx) return; const ctx = new Ctx(); const osc = ctx.createOscillator(); const gain = ctx.createGain(); const notes = { water: [520, 720], harvest: [440, 660, 880], pet: [330, 392, 494], plant: [260, 330], day: [392, 494, 659], click: [180, 240], purr: [92, 110, 130], bee: [244, 320, 410] }[kind]; osc.type = kind === "water" || kind === "purr" ? "sine" : "triangle"; osc.frequency.setValueAtTime(notes[0], ctx.currentTime); notes.slice(1).forEach((n, i) => osc.frequency.linearRampToValueAtTime(n, ctx.currentTime + (i + 1) * .11)); gain.gain.setValueAtTime(.0001, ctx.currentTime); gain.gain.exponentialRampToValueAtTime(.055 * volume, ctx.currentTime + .025); gain.gain.exponentialRampToValueAtTime(.0001, ctx.currentTime + (kind === "purr" ? .7 : .42)); osc.connect(gain).connect(ctx.destination); osc.start(); osc.stop(ctx.currentTime + .45); } catch { /* Audio is an enhancement, never a blocker. */ }
}

export default function GameCanvas() {
  const canvasRef = useRef<HTMLCanvasElement>(null); const startedRef = useRef(false);
  const [save, setSave] = useState<SaveData>(loadSave); const [message, setMessage] = useState("Nắng vừa đủ cho một ngày xanh."); const [showSeeds, setShowSeeds] = useState(false); const [showDecor, setShowDecor] = useState(false); const [storyOpen, setStoryOpen] = useState(() => !loadSave().storySeen); const [cursor, setCursor] = useState({ x: 48, y: 58 }); const [bee, setBee] = useState({ x: 70, y: 26 }); const [petting, setPetting] = useState(false); const [clock, setClock] = useState(() => new Date()); const ambienceRef = useRef<AudioContext | null>(null);
  const { plots, water, leaves, selectedPlot, selectedPet, petMood, day, seeds, decor, soundOn, selectedSeed, luckyDew, stickers, musicVolume, sfxVolume } = save;
  const season = ["Xuân nảy mầm", "Hạ rực rỡ", "Thu dịu vàng", "Đông êm"][(day - 1) % 4];
  const hour = clock.getHours() + clock.getMinutes() / 60; const lightMode = hour < 6 ? "night" : hour < 11 ? "morning" : hour < 17 ? "daylight" : hour < 20 ? "sunset" : "night";
  const weather = ["Mây mỏng trôi qua", "Nắng mật ong", "Mưa bụi rất khẽ", "Sương đêm dịu dàng"][(Math.floor(clock.getHours() / 5)) % 4];
  const seasonTask = ["Gieo một mầm mới và vuốt ve bạn nhỏ.", "Tưới hai luống cây dưới nắng.", "Thu hoạch một món quà từ đất.", "Trang trí một góc vườn cho ấm áp."][(day - 1) % 4];
  const completed = useMemo(() => plots.filter((plot) => plot.state === "ready").length, [plots]);
  const startAmbience = () => { if (!soundOn || ambienceRef.current || typeof window === "undefined") return; const Ctx = window.AudioContext || (window as typeof window & { webkitAudioContext?: typeof AudioContext }).webkitAudioContext; if (!Ctx) return; const ctx = new Ctx(); const gain = ctx.createGain(); gain.gain.value = .012 * musicVolume; gain.connect(ctx.destination); [174, 261.63].forEach((frequency, index) => { const oscillator = ctx.createOscillator(); oscillator.type = index ? "sine" : "triangle"; oscillator.frequency.value = frequency; oscillator.connect(gain); oscillator.start(); }); ambienceRef.current = ctx; };
  useEffect(() => { localStorage.setItem(SAVE_KEY, JSON.stringify(save)); }, [save]);
  useEffect(() => { const id = window.setInterval(() => setClock(new Date()), 30000); return () => window.clearInterval(id); }, []);
  useEffect(() => { const canvas = canvasRef.current; if (!canvas || startedRef.current) return; startedRef.current = true; const engine = new Engine(canvas, true, { preserveDrawingBuffer: true, stencil: true, adaptToDeviceRatio: true }); let disposed = false; createGameScene(engine, canvas).then(({ scene, dispose }) => { if (disposed) return; engine.runRenderLoop(() => scene.render()); const onResize = () => engine.resize(); window.addEventListener("resize", onResize); (engine as Engine & { __cleanup?: () => void }).__cleanup = () => { window.removeEventListener("resize", onResize); dispose(); }; }); return () => { disposed = true; (engine as Engine & { __cleanup?: () => void }).__cleanup?.(); engine.dispose(); startedRef.current = false; }; }, []);
  useEffect(() => { if (new URLSearchParams(window.location.search).has("demo")) { setMessage("Một ngày mới, vài mầm cây đang chờ bạn."); setSave((s) => ({ ...s, selectedPlot: 3 })); } }, []);
  const update = (patch: Partial<SaveData>) => setSave((current) => ({ ...current, ...patch }));
  const handleGardenMove = (event: MouseEvent<HTMLElement>) => { const rect = event.currentTarget.getBoundingClientRect(); const next = { x: ((event.clientX - rect.left) / rect.width) * 100, y: ((event.clientY - rect.top) / rect.height) * 100 }; setCursor(next); setBee({ x: next.x - 7, y: next.y - 8 }); startAmbience(); }; const handleGardenPointer = (event: PointerEvent<HTMLElement>) => { const rect = event.currentTarget.getBoundingClientRect(); const next = { x: ((event.clientX - rect.left) / rect.width) * 100, y: ((event.clientY - rect.top) / rect.height) * 100 }; setCursor(next); setBee({ x: next.x - 7, y: next.y - 8 }); startAmbience(); }; const handlePetMove = () => { setPetting(true); setMessage(`${selectedPet} lim dim vì được bạn chải lông.`); playTone("purr", soundOn, sfxVolume); update({ petMood: Math.min(100, petMood + 1) }); }; const handlePetRelease = () => setPetting(false); const beePollinate = () => { const target = plots.findIndex((plot) => plot.state === "sprout" || plot.state === "growing"); if (target < 0) { setMessage("Ong đang lượn một vòng quanh những mầm cây đã lớn."); playTone("bee", soundOn, sfxVolume); return; } update({ luckyDew: luckyDew + 1, plots: plots.map((plot, index) => index === target ? { ...plot, state: plot.progress + 12 >= 100 ? "ready" : "growing", progress: Math.min(100, plot.progress + 12) } : plot) }); setMessage("Ong vừa đậu xuống. Một Giọt Sương May Mắn nằm lại trên lá."); playTone("bee", soundOn, sfxVolume); toast("Thụ phấn may mắn", { description: "+1 Giọt Sương May Mắn" }); }; const collectBeeSticker = () => { const available = (Object.keys(stickerCatalog) as StickerKey[]).filter((key) => !stickers.includes(key)); const key = available[Math.floor(Math.random() * available.length)] ?? "lucky"; const nextStickers = available.length ? [...stickers, key] : stickers; update({ stickers: nextStickers }); setMessage(stickerCatalog[key].note); playTone("bee", soundOn, sfxVolume); toast(`Sticker ${stickerCatalog[key].icon}`, { description: stickerCatalog[key].note }); };
  const plant = () => { startAmbience(); if (seeds[selectedSeed] <= 0) { toast("Hết hạt giống", { description: "Hãy mở khóa thêm hạt trong mùa này." }); return; } if (plots[selectedPlot].state !== "empty") { toast("Luống này đã có cây", { description: "Bạn có thể chọn luống trống khác." }); return; } const seed = seedCatalog[selectedSeed]; const nextSeeds = { ...seeds, [selectedSeed]: seeds[selectedSeed] - 1 }; update({ seeds: nextSeeds, plots: plots.map((plot, i) => i === selectedPlot ? { state: "sprout", plant: seed.label, progress: 12 } : plot) }); setMessage(`${seed.label} đã nằm yên trong đất.`); playTone("plant", soundOn, sfxVolume); toast("Đã gieo hạt", { description: `${seed.label} — hãy tưới một chút.` }); };
  const waterPlot = () => { startAmbience(); if (!water) { toast("Bình tưới đang trống", { description: "Nước sẽ đầy lại vào ngày mai." }); return; } if (plots[selectedPlot].state === "empty") { toast("Luống này còn trống", { description: "Gieo một hạt trước nhé." }); return; } update({ water: water - 1, plots: plots.map((plot, i) => i === selectedPlot ? { ...plot, state: plot.progress >= 68 ? "ready" : "growing", progress: Math.min(100, plot.progress + 18) } : plot) }); setMessage("Từng giọt nước làm khu vườn thức dậy."); playTone("water", soundOn, sfxVolume); };
  const harvest = () => { startAmbience(); if (plots[selectedPlot].state !== "ready") { toast("Cây vẫn đang lớn", { description: "Bạn có thể tưới thêm để giúp cây nhanh hơn." }); return; } update({ leaves: leaves + 8, plots: plots.map((plot, i) => i === selectedPlot ? { state: "empty", plant: "", progress: 0 } : plot) }); setMessage("Một mùa nhỏ đã hoàn thành. Lá mới lại có thể bắt đầu."); playTone("harvest", soundOn, sfxVolume); toast("Thu hoạch vui quá", { description: "+8 lá xanh" }); };
  const pet = () => { startAmbience(); update({ petMood: Math.min(100, petMood + 7) }); setMessage(`${selectedPet} khẽ dụi đầu vào tay bạn.`); playTone("pet", soundOn, sfxVolume); toast(`Đã vuốt ve ${selectedPet}`, { description: "Niềm vui +7" }); };
  const nextDay = () => { update({ day: day + 1, water: 6, petMood: Math.max(65, petMood - 2), plots: plots.map((plot) => plot.state === "sprout" ? { ...plot, state: "growing", progress: plot.progress + 18 } : plot) }); setMessage(`Mùa ${season} vừa khép lại, một ngày mới bắt đầu.`); playTone("day", soundOn, sfxVolume); };
  const buyDecor = (key: DecorKey) => { const item = decorCatalog[key]; if (decor.includes(key)) return; if (leaves < item.cost) { toast("Chưa đủ lá xanh", { description: `Cần ${item.cost} lá để mở khóa ${item.label}.` }); return; } update({ leaves: leaves - item.cost, decor: [...decor, key] }); setMessage(`${item.label} đã tìm được một góc nhỏ trong vườn.`); playTone("harvest", soundOn, sfxVolume); };
  const resetSave = () => { localStorage.removeItem(SAVE_KEY); setSave(defaultSave); setMessage("Khu vườn đã trở về ngày đầu tiên."); toast("Đã xóa tiến trình trên thiết bị"); };

  return <main className="garden-shell"><canvas ref={canvasRef} className="garden-canvas" aria-hidden="true" /><div className="garden-art" aria-hidden="true" /><header className="topbar"><div className="brand-lockup"><span className="brand-mark"><img src={logoUrl} alt="" onError={(e) => { e.currentTarget.style.display = "none"; }} /><span className="brand-mark-fallback">⌁</span></span><div><p className="eyebrow">NHẬT KÝ VƯỜN</p><h1>Vườn Nhỏ <em>Chill</em></h1></div></div><div className="top-actions"><div className="season-chip"><Sun size={14} /><span>{season}</span></div><div className="weather-chip" title="Thời tiết thay đổi theo thời gian thực"><span>{lightMode === "night" ? "☾" : lightMode === "sunset" ? "◒" : "☼"}</span><span>{weather}</span></div><button className="sound-toggle" onClick={() => update({ soundOn: !soundOn })} aria-label={soundOn ? "Tắt âm thanh" : "Bật âm thanh"}>{soundOn ? <Volume2 size={16} /> : <VolumeX size={16} />}</button><div className="day-card"><Sun size={16} /><span>Ngày {day}</span><button onClick={nextDay} aria-label="Sang ngày mới"><RotateCcw size={14} /></button></div></div></header>
  <section className="game-layout"><div className={`playfield light-${lightMode}`} aria-label="Khu vườn tương tác" onMouseMove={handleGardenMove} onPointerMove={handleGardenPointer} onClick={() => playTone("click", soundOn, sfxVolume)}><div className="welcome-note"><Sparkles size={15} /><span>{message}</span></div><div className="plots-row">{plots.map((plot, index) => <button key={index} className={`plot plot-${plot.state} ${selectedPlot === index ? "is-selected" : ""}`} onClick={() => update({ selectedPlot: index })} aria-label={`Luống ${index + 1}: ${stageCopy[plot.state]}`}><span className="plot-soil" />{plot.state !== "empty" && <span className={`plant-illustration plant-${plot.state}`}>{plot.state === "ready" ? (plot.plant.includes("Dâu") ? "🍓" : plot.plant.includes("Hướng") ? "🌻" : "🍅") : plot.state === "growing" ? "🌿" : "🌱"}</span>}<span className="plot-label">{plot.state === "empty" ? "Gieo hạt" : plot.plant || stageCopy[plot.state]}</span>{plot.state !== "empty" && <span className="plot-progress"><span style={{ width: `${plot.progress}%` }} /></span>}</button>)}</div><div className="decor-layer">{decor.map((item) => <span key={item} title={decorCatalog[item].label}>{decorCatalog[item].icon}</span>)}</div><div className="cursor-whisper" style={{ left: `${cursor.x}%`, top: `${cursor.y}%` }} aria-hidden="true">✦</div><button className="lucky-bee" style={{ left: `${bee.x}%`, top: `${bee.y}%` }} onClick={(event) => { event.stopPropagation(); collectBeeSticker(); }} onDoubleClick={(event) => { event.stopPropagation(); beePollinate(); }} aria-label="Ong may mắn: nhấp để nhận sticker, nhấp đúp để thụ phấn"><span className="bee-body">🐝</span><span className="bee-jar">🍯</span><i>🍀</i></button><div className="garden-pets" aria-label="Hai người bạn trong vườn"><button className={`pet-hotspot cat-hotspot ${selectedPet === "Miu" ? "pet-selected" : ""} ${petting && selectedPet === "Miu" ? "is-petting" : ""}`} onClick={() => update({ selectedPet: "Miu" })} onPointerDown={handlePetMove} onPointerMove={(event) => { if (event.buttons) handlePetMove(); }} onPointerUp={handlePetRelease} onPointerLeave={handlePetRelease} onMouseMove={handlePetMove} onMouseLeave={handlePetRelease} aria-label="Chọn và vuốt ve Miu"><span className="pet-emoji"><Cat size={25} /></span><b>Miu</b></button><button className={`pet-hotspot rabbit-hotspot ${selectedPet === "Bông" ? "pet-selected" : ""} ${petting && selectedPet === "Bông" ? "is-petting" : ""}`} onClick={() => update({ selectedPet: "Bông" })} onPointerDown={handlePetMove} onPointerMove={(event) => { if (event.buttons) handlePetMove(); }} onPointerUp={handlePetRelease} onPointerLeave={handlePetRelease} onMouseMove={handlePetMove} onMouseLeave={handlePetRelease} aria-label="Chọn và vuốt ve Bông"><span className="pet-emoji"><Rabbit size={25} /></span><b>Bông</b></button></div><div className="floating-leaf leaf-one">✦</div><div className="floating-leaf leaf-two">✦</div></div>
  <aside className="side-panel"><div className="note-sheet mission-sheet refuge-sheet"><div className="pin" /><p className="eyebrow">GÓC NHỎ CỦA RIÊNG BẠN</p><h2>Không cần vội.</h2><p className="soft-copy">{seasonTask} Nhưng bạn không cần hoàn thành gì cả. Khu vườn vẫn ở đây, yên lặng chờ bạn trở về.</p><div className="quiet-line"><span>♪ một khoảng trời nhỏ</span><span>{season}</span></div></div><div className="note-sheet pet-sheet"><div className="pet-heading"><div><p className="eyebrow">BẠN ĐỒNG HÀNH</p><h2>{selectedPet}</h2></div><Heart size={19} fill="currentColor" /></div><p className="soft-copy">Đang ngồi dưới bóng cây, chờ bạn để ý.</p><div className="stat-line"><span>Vui vẻ</span><strong>{petMood}%</strong></div><div className="stat-bar"><span style={{ width: `${petMood}%` }} /></div><button className="soft-button" onClick={pet}><Hand size={16} /> Vuốt ve một chút</button></div><div className="resource-strip"><div><Droplets size={15} /><span>Nước</span><strong>{water}</strong></div><div><Leaf size={15} /><span>Lá</span><strong>{leaves}</strong></div><div><span>🍀</span><span>Sương</span><strong>{luckyDew}</strong></div></div><div className="volume-sheet"><div><span>♪ Nhạc nền</span><input aria-label="Âm lượng nhạc nền" type="range" min="0" max="1" step=".01" value={musicVolume} onChange={(event) => update({ musicVolume: Number(event.target.value) })} /></div><div><span>✦ Hiệu ứng</span><input aria-label="Âm lượng hiệu ứng" type="range" min="0" max="1" step=".01" value={sfxVolume} onChange={(event) => update({ sfxVolume: Number(event.target.value) })} /></div><small>Sticker ong: {stickers.length}/4</small></div></aside></section>
  <nav className="tool-drawer" aria-label="Dụng cụ làm vườn"><div className="tool-intro"><Shovel size={19} /><span>Hôm nay làm gì?</span></div><button className="tool-button" onClick={() => setShowSeeds(!showSeeds)}><span className="tool-icon">🌰</span><span>Hạt giống</span><small>{seedCatalog[selectedSeed].label}</small></button><button className="tool-button" onClick={waterPlot}><span className="tool-icon">💧</span><span>Tưới cây</span><small>{water} giọt còn lại</small></button><button className="tool-button" onClick={harvest}><span className="tool-icon">🧺</span><span>Thu hoạch</span><small>Luống đã chín</small></button><button className="tool-button" onClick={() => setShowDecor(!showDecor)}><span className="tool-icon">🪴</span><span>Trang trí</span><small>{decor.length}/3 món</small></button><div className="tool-tip"><Sprout size={17} /><span>Chậm lại một nhịp.<br /><b>Mầm cây sẽ lo phần còn lại.</b></span></div></nav>
  {showSeeds && <div className="collection-popover seed-popover"><div className="popover-head"><span><Sprout size={15} /> Hạt giống trong túi</span><button onClick={() => setShowSeeds(false)}>×</button></div><div className="collection-grid">{(Object.keys(seedCatalog) as SeedKey[]).map((key) => <button key={key} className={`collection-item ${selectedSeed === key ? "chosen" : ""}`} onClick={() => { update({ selectedSeed: key }); setShowSeeds(false); }}><span>{seedCatalog[key].icon}</span><b>{seedCatalog[key].label}</b><small>{seeds[key]} hạt · {seedCatalog[key].days}</small></button>)}</div><button className="primary-action" onClick={plant}>Gieo vào luống đang chọn</button></div>}
  {showDecor && <div className="collection-popover decor-popover"><div className="popover-head"><span><Flower2 size={15} /> Góc nhỏ theo mùa</span><button onClick={() => setShowDecor(false)}>×</button></div><p className="popover-note">Mở khóa bằng lá xanh. Món đã mở sẽ xuất hiện trong vườn.</p><div className="collection-grid">{(Object.keys(decorCatalog) as DecorKey[]).map((key) => { const item = decorCatalog[key]; const owned = decor.includes(key); return <button key={key} className={`collection-item ${owned ? "chosen" : ""}`} onClick={() => buyDecor(key)}><span>{item.icon}</span><b>{item.label}</b><small>{owned ? "Đã đặt trong vườn" : `${item.cost} lá xanh`} {owned ? <TreePine size={12} /> : <LockKeyhole size={11} />}</small></button>; })}</div></div>}
  {storyOpen && <div className="story-veil"><section className="story-card"><div className="story-key">⌁</div><p className="eyebrow">GÓC NHỎ TRỐN LOÀI NGƯỜI</p><h2>Chiếc chìa khóa bí mật</h2><p>Bên ngoài, thế giới có thể quá ồn. Nhưng trong lòng bàn tay bạn có một chiếc chìa khóa mở ra không gian túi chỉ thuộc về riêng bạn — nơi có chậu cây nhỏ, tiếng nước rơi và những người bạn không bao giờ hỏi bạn phải trở thành ai.</p><p>Hãy ghé qua khi muốn. Ở đây không có bảng xếp hạng, không có đồng hồ đếm ngược, cũng không có điều gì bắt buộc.</p><button className="primary-action" onClick={() => { update({ storySeen: true }); setStoryOpen(false); startAmbience(); playTone("click", soundOn, sfxVolume); }}>Mở cánh cửa nhỏ</button></section></div>}<button className="reset-save" onClick={resetSave} aria-label="Xóa tiến trình và bắt đầu lại">Bắt đầu lại</button></main>;
}
