// Style reminder: Nắng Trên Luống Đất — mọi phản hồi là một dấu hiệu chăm sóc nhỏ, với paper UI và Clay Sprout #C9784B.
import { useEffect, useMemo, useRef, useState } from "react";
import { Engine } from "@babylonjs/core/Engines/engine";
import { createGameScene } from "@/game/scene";
import { Leaf, Droplets, Heart, Sun, Sprout, Shovel, Hand, Sparkles, Cat, Rabbit, RotateCcw, Volume2, VolumeX, Flower2, TreePine, Bird, LockKeyhole } from "lucide-react";
import { toast } from "sonner";

const logoUrl = "/manus-storage/vuon-nho-logo_98aa6ada.png";
const SAVE_KEY = "vuon-nho-chill-save-v2";
type PlotState = "empty" | "sprout" | "growing" | "ready";
type Plot = { state: PlotState; plant: string; progress: number };
type PetName = "Miu" | "Bông";
type SeedKey = "sunflower" | "tomato" | "lavender" | "strawberry";
type DecorKey = "bench" | "birdhouse" | "lantern";
type SaveData = { plots: Plot[]; water: number; leaves: number; selectedPlot: number; selectedPet: PetName; petMood: number; day: number; seeds: Record<SeedKey, number>; decor: DecorKey[]; soundOn: boolean; selectedSeed: SeedKey };

const initialPlots: Plot[] = [
  { state: "ready", plant: "Cà chua bi", progress: 100 }, { state: "growing", plant: "Húng quế", progress: 68 },
  { state: "sprout", plant: "Hoa cúc", progress: 28 }, { state: "empty", plant: "", progress: 0 },
];
const seedCatalog: Record<SeedKey, { label: string; icon: string; days: string; color: string }> = {
  sunflower: { label: "Hướng dương", icon: "🌻", days: "3 ngày", color: "#e9b85e" }, tomato: { label: "Cà chua bi", icon: "🍅", days: "2 ngày", color: "#db7562" }, lavender: { label: "Oải hương", icon: "💜", days: "4 ngày", color: "#a58abf" }, strawberry: { label: "Dâu nhỏ", icon: "🍓", days: "3 ngày", color: "#d86668" },
};
const decorCatalog: Record<DecorKey, { label: string; icon: string; cost: number }> = { bench: { label: "Ghế gỗ", icon: "🪵", cost: 18 }, birdhouse: { label: "Nhà chim", icon: "🐦", cost: 26 }, lantern: { label: "Đèn lồng", icon: "🏮", cost: 34 } };
const stageCopy: Record<PlotState, string> = { empty: "Luống trống", sprout: "Mầm non", growing: "Đang lớn", ready: "Thu hoạch" };
const defaultSave: SaveData = { plots: initialPlots, water: 6, leaves: 24, selectedPlot: 0, selectedPet: "Miu", petMood: 82, day: 7, seeds: { sunflower: 3, tomato: 2, lavender: 1, strawberry: 1 }, decor: [], soundOn: true, selectedSeed: "sunflower" };

function loadSave(): SaveData { try { const raw = localStorage.getItem(SAVE_KEY); return raw ? { ...defaultSave, ...JSON.parse(raw) } : defaultSave; } catch { return defaultSave; } }
function playTone(kind: "water" | "harvest" | "pet" | "plant" | "day", enabled: boolean) {
  if (!enabled || typeof window === "undefined") return;
  try { const Ctx = window.AudioContext || (window as typeof window & { webkitAudioContext?: typeof AudioContext }).webkitAudioContext; if (!Ctx) return; const ctx = new Ctx(); const osc = ctx.createOscillator(); const gain = ctx.createGain(); const notes = { water: [520, 720], harvest: [440, 660, 880], pet: [330, 392, 494], plant: [260, 330], day: [392, 494, 659] }[kind]; osc.type = kind === "water" ? "sine" : "triangle"; osc.frequency.setValueAtTime(notes[0], ctx.currentTime); notes.slice(1).forEach((n, i) => osc.frequency.linearRampToValueAtTime(n, ctx.currentTime + (i + 1) * .11)); gain.gain.setValueAtTime(.0001, ctx.currentTime); gain.gain.exponentialRampToValueAtTime(.055, ctx.currentTime + .025); gain.gain.exponentialRampToValueAtTime(.0001, ctx.currentTime + .42); osc.connect(gain).connect(ctx.destination); osc.start(); osc.stop(ctx.currentTime + .45); } catch { /* Audio is an enhancement, never a blocker. */ }
}

export default function GameCanvas() {
  const canvasRef = useRef<HTMLCanvasElement>(null); const startedRef = useRef(false);
  const [save, setSave] = useState<SaveData>(loadSave); const [message, setMessage] = useState("Nắng vừa đủ cho một ngày xanh."); const [showSeeds, setShowSeeds] = useState(false); const [showDecor, setShowDecor] = useState(false);
  const { plots, water, leaves, selectedPlot, selectedPet, petMood, day, seeds, decor, soundOn, selectedSeed } = save;
  const season = ["Xuân nảy mầm", "Hạ rực rỡ", "Thu dịu vàng", "Đông êm"][(day - 1) % 4];
  const seasonTask = ["Gieo một mầm mới và vuốt ve bạn nhỏ.", "Tưới hai luống cây dưới nắng.", "Thu hoạch một món quà từ đất.", "Trang trí một góc vườn cho ấm áp."][(day - 1) % 4];
  const completed = useMemo(() => plots.filter((plot) => plot.state === "ready").length, [plots]);
  useEffect(() => { localStorage.setItem(SAVE_KEY, JSON.stringify(save)); }, [save]);
  useEffect(() => { const canvas = canvasRef.current; if (!canvas || startedRef.current) return; startedRef.current = true; const engine = new Engine(canvas, true, { preserveDrawingBuffer: true, stencil: true, adaptToDeviceRatio: true }); let disposed = false; createGameScene(engine, canvas).then(({ scene, dispose }) => { if (disposed) return; engine.runRenderLoop(() => scene.render()); const onResize = () => engine.resize(); window.addEventListener("resize", onResize); (engine as Engine & { __cleanup?: () => void }).__cleanup = () => { window.removeEventListener("resize", onResize); dispose(); }; }); return () => { disposed = true; (engine as Engine & { __cleanup?: () => void }).__cleanup?.(); engine.dispose(); startedRef.current = false; }; }, []);
  useEffect(() => { if (new URLSearchParams(window.location.search).has("demo")) { setMessage("Một ngày mới, vài mầm cây đang chờ bạn."); setSave((s) => ({ ...s, selectedPlot: 3 })); } }, []);
  const update = (patch: Partial<SaveData>) => setSave((current) => ({ ...current, ...patch }));
  const plant = () => { if (seeds[selectedSeed] <= 0) { toast("Hết hạt giống", { description: "Hãy mở khóa thêm hạt trong mùa này." }); return; } if (plots[selectedPlot].state !== "empty") { toast("Luống này đã có cây", { description: "Bạn có thể chọn luống trống khác." }); return; } const seed = seedCatalog[selectedSeed]; const nextSeeds = { ...seeds, [selectedSeed]: seeds[selectedSeed] - 1 }; update({ seeds: nextSeeds, plots: plots.map((plot, i) => i === selectedPlot ? { state: "sprout", plant: seed.label, progress: 12 } : plot) }); setMessage(`${seed.label} đã nằm yên trong đất.`); playTone("plant", soundOn); toast("Đã gieo hạt", { description: `${seed.label} — hãy tưới một chút.` }); };
  const waterPlot = () => { if (!water) { toast("Bình tưới đang trống", { description: "Nước sẽ đầy lại vào ngày mai." }); return; } if (plots[selectedPlot].state === "empty") { toast("Luống này còn trống", { description: "Gieo một hạt trước nhé." }); return; } update({ water: water - 1, plots: plots.map((plot, i) => i === selectedPlot ? { ...plot, state: plot.progress >= 68 ? "ready" : "growing", progress: Math.min(100, plot.progress + 18) } : plot) }); setMessage("Từng giọt nước làm khu vườn thức dậy."); playTone("water", soundOn); };
  const harvest = () => { if (plots[selectedPlot].state !== "ready") { toast("Cây vẫn đang lớn", { description: "Bạn có thể tưới thêm để giúp cây nhanh hơn." }); return; } update({ leaves: leaves + 8, plots: plots.map((plot, i) => i === selectedPlot ? { state: "empty", plant: "", progress: 0 } : plot) }); setMessage("Một mùa nhỏ đã hoàn thành. Lá mới lại có thể bắt đầu."); playTone("harvest", soundOn); toast("Thu hoạch vui quá", { description: "+8 lá xanh" }); };
  const pet = () => { update({ petMood: Math.min(100, petMood + 7) }); setMessage(`${selectedPet} khẽ dụi đầu vào tay bạn.`); playTone("pet", soundOn); toast(`Đã vuốt ve ${selectedPet}`, { description: "Niềm vui +7" }); };
  const nextDay = () => { update({ day: day + 1, water: 6, petMood: Math.max(65, petMood - 2), plots: plots.map((plot) => plot.state === "sprout" ? { ...plot, state: "growing", progress: plot.progress + 18 } : plot) }); setMessage(`Mùa ${season} vừa khép lại, một ngày mới bắt đầu.`); playTone("day", soundOn); };
  const buyDecor = (key: DecorKey) => { const item = decorCatalog[key]; if (decor.includes(key)) return; if (leaves < item.cost) { toast("Chưa đủ lá xanh", { description: `Cần ${item.cost} lá để mở khóa ${item.label}.` }); return; } update({ leaves: leaves - item.cost, decor: [...decor, key] }); setMessage(`${item.label} đã tìm được một góc nhỏ trong vườn.`); playTone("harvest", soundOn); };
  const resetSave = () => { localStorage.removeItem(SAVE_KEY); setSave(defaultSave); setMessage("Khu vườn đã trở về ngày đầu tiên."); toast("Đã xóa tiến trình trên thiết bị"); };

  return <main className="garden-shell"><canvas ref={canvasRef} className="garden-canvas" aria-hidden="true" /><div className="garden-art" aria-hidden="true" /><header className="topbar"><div className="brand-lockup"><span className="brand-mark"><img src={logoUrl} alt="" onError={(e) => { e.currentTarget.style.display = "none"; }} /><span className="brand-mark-fallback">⌁</span></span><div><p className="eyebrow">NHẬT KÝ VƯỜN</p><h1>Vườn Nhỏ <em>Chill</em></h1></div></div><div className="top-actions"><div className="season-chip"><Sun size={14} /><span>{season}</span></div><button className="sound-toggle" onClick={() => update({ soundOn: !soundOn })} aria-label={soundOn ? "Tắt âm thanh" : "Bật âm thanh"}>{soundOn ? <Volume2 size={16} /> : <VolumeX size={16} />}</button><div className="day-card"><Sun size={16} /><span>Ngày {day}</span><button onClick={nextDay} aria-label="Sang ngày mới"><RotateCcw size={14} /></button></div></div></header>
  <section className="game-layout"><div className="playfield" aria-label="Khu vườn tương tác"><div className="welcome-note"><Sparkles size={15} /><span>{message}</span></div><div className="plots-row">{plots.map((plot, index) => <button key={index} className={`plot plot-${plot.state} ${selectedPlot === index ? "is-selected" : ""}`} onClick={() => update({ selectedPlot: index })} aria-label={`Luống ${index + 1}: ${stageCopy[plot.state]}`}><span className="plot-soil" />{plot.state !== "empty" && <span className={`plant-illustration plant-${plot.state}`}>{plot.state === "ready" ? (plot.plant.includes("Dâu") ? "🍓" : plot.plant.includes("Hướng") ? "🌻" : "🍅") : plot.state === "growing" ? "🌿" : "🌱"}</span>}<span className="plot-label">{plot.state === "empty" ? "Gieo hạt" : plot.plant || stageCopy[plot.state]}</span>{plot.state !== "empty" && <span className="plot-progress"><span style={{ width: `${plot.progress}%` }} /></span>}</button>)}</div><div className="decor-layer">{decor.map((item) => <span key={item} title={decorCatalog[item].label}>{decorCatalog[item].icon}</span>)}</div><div className="garden-pets" aria-label="Hai người bạn trong vườn"><button className={`pet-hotspot cat-hotspot ${selectedPet === "Miu" ? "pet-selected" : ""}`} onClick={() => update({ selectedPet: "Miu" })} aria-label="Chọn Miu"><span className="pet-emoji"><Cat size={25} /></span><b>Miu</b></button><button className={`pet-hotspot rabbit-hotspot ${selectedPet === "Bông" ? "pet-selected" : ""}`} onClick={() => update({ selectedPet: "Bông" })} aria-label="Chọn Bông"><span className="pet-emoji"><Rabbit size={25} /></span><b>Bông</b></button></div><div className="floating-leaf leaf-one">✦</div><div className="floating-leaf leaf-two">✦</div></div>
  <aside className="side-panel"><div className="note-sheet mission-sheet"><div className="pin" /><p className="eyebrow">NHIỆM VỤ {season.toUpperCase()}</p><h2>Chạm đất, chạm vui.</h2><p className="soft-copy">{seasonTask}</p><div className="mission-progress"><span style={{ width: `${Math.min(100, completed * 40 + (petMood > 80 ? 20 : 0))}%` }} /></div><div className="mission-meta"><span>{completed}/2 việc đã xong</span><Leaf size={15} /></div></div><div className="note-sheet pet-sheet"><div className="pet-heading"><div><p className="eyebrow">BẠN ĐỒNG HÀNH</p><h2>{selectedPet}</h2></div><Heart size={19} fill="currentColor" /></div><p className="soft-copy">Đang ngồi dưới bóng cây, chờ bạn để ý.</p><div className="stat-line"><span>Vui vẻ</span><strong>{petMood}%</strong></div><div className="stat-bar"><span style={{ width: `${petMood}%` }} /></div><button className="soft-button" onClick={pet}><Hand size={16} /> Vuốt ve một chút</button></div><div className="resource-strip"><div><Droplets size={15} /><span>Nước</span><strong>{water}</strong></div><div><Leaf size={15} /><span>Lá</span><strong>{leaves}</strong></div></div></aside></section>
  <nav className="tool-drawer" aria-label="Dụng cụ làm vườn"><div className="tool-intro"><Shovel size={19} /><span>Hôm nay làm gì?</span></div><button className="tool-button" onClick={() => setShowSeeds(!showSeeds)}><span className="tool-icon">🌰</span><span>Hạt giống</span><small>{seedCatalog[selectedSeed].label}</small></button><button className="tool-button" onClick={waterPlot}><span className="tool-icon">💧</span><span>Tưới cây</span><small>{water} giọt còn lại</small></button><button className="tool-button" onClick={harvest}><span className="tool-icon">🧺</span><span>Thu hoạch</span><small>Luống đã chín</small></button><button className="tool-button" onClick={() => setShowDecor(!showDecor)}><span className="tool-icon">🪴</span><span>Trang trí</span><small>{decor.length}/3 món</small></button><div className="tool-tip"><Sprout size={17} /><span>Chậm lại một nhịp.<br /><b>Mầm cây sẽ lo phần còn lại.</b></span></div></nav>
  {showSeeds && <div className="collection-popover seed-popover"><div className="popover-head"><span><Sprout size={15} /> Hạt giống trong túi</span><button onClick={() => setShowSeeds(false)}>×</button></div><div className="collection-grid">{(Object.keys(seedCatalog) as SeedKey[]).map((key) => <button key={key} className={`collection-item ${selectedSeed === key ? "chosen" : ""}`} onClick={() => { update({ selectedSeed: key }); setShowSeeds(false); }}><span>{seedCatalog[key].icon}</span><b>{seedCatalog[key].label}</b><small>{seeds[key]} hạt · {seedCatalog[key].days}</small></button>)}</div><button className="primary-action" onClick={plant}>Gieo vào luống đang chọn</button></div>}
  {showDecor && <div className="collection-popover decor-popover"><div className="popover-head"><span><Flower2 size={15} /> Góc nhỏ theo mùa</span><button onClick={() => setShowDecor(false)}>×</button></div><p className="popover-note">Mở khóa bằng lá xanh. Món đã mở sẽ xuất hiện trong vườn.</p><div className="collection-grid">{(Object.keys(decorCatalog) as DecorKey[]).map((key) => { const item = decorCatalog[key]; const owned = decor.includes(key); return <button key={key} className={`collection-item ${owned ? "chosen" : ""}`} onClick={() => buyDecor(key)}><span>{item.icon}</span><b>{item.label}</b><small>{owned ? "Đã đặt trong vườn" : `${item.cost} lá xanh`} {owned ? <TreePine size={12} /> : <LockKeyhole size={11} />}</small></button>; })}</div></div>}
  <button className="reset-save" onClick={resetSave} aria-label="Xóa tiến trình và bắt đầu lại">Bắt đầu lại</button></main>;
}
